### PR TITLE
Update script/updateHfDataset file for 2024 data batch.

### PR DESCRIPTION
**Pull request by traycn**
Fixes #{issue number here}

  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Review by edwinjue — APPROVED** [review]
LGTM!

**Comment by ryanfchase** [comment]
@traycn FYI please be sure to change `Fixes #{issue number here}` to `Fixes #1644` so that github can track which issue this PR is associated with! You can do so for the next PR.

**Comment by edwinjue** [comment]
@traycn @ryanfchase please see https://github.com/hackforla/311-data/issues/1644#issuecomment-1909380140

**Comment by traycn** [comment]
Thanks for the catch @edwinjue ! Created a PR updating this url value.

PR - https://github.com/hackforla/311-data/pull/1657

**Pull request merged**
