### PR TITLE
PM: Modify template for post-an-open-role.md

### PR DESCRIPTION
**Pull request by ryanfchase**
Fixes #{issue number here}

  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Comment by Skydodle** [comment]
---
name: Post an open role
about: Recruit volunteers for specific open roles template
title: '311 Data: Open Role for: [Replace with NAME OF ROLE]'
labels: 'size: 0.25pt,feature: recruiting,Role: Missing'
assignees: ''

---

image

[INSERT DRAFT FROM THE Recruit volunteers for team open roles issue]

**Comment by Skydodle** [comment]
> name: Post an open role about: Recruit volunteers for specific open roles template title: '311 Data: Open Role for: [Replace with NAME OF ROLE]' labels: 'size: 0.25pt,feature: recruiting,Role: Missing' assignees: ''
> 
> image
> 
> [INSERT DRAFT FROM THE Recruit volunteers for team open roles issue]

Just testing the template here in markdown. The img url seems unusually long and it does'nt work?

**Comment by ryanfchase** [comment]
@Skydodle yeah looks like Bonnie committed directly to the branch with this template. This PR can reflect changes to make it specific to our team. The image she picked is better. You can also see this template already in action at these links:
- https://github.com/hackforla/311-data/issues/1771
- https://github.com/hackforla/311-data/issues/1772
- https://github.com/hackforla/311-data/issues/1773
- https://github.com/hackforla/311-data/issues/1774

**Review by Skydodle — APPROVED** [review]
Looks good to me. Thanks Ryan

**Pull request merged**
