### PR TITLE
1676 Update loading modals to new design

### LINKED ISSUE #1676: Update Loading Modals (Dev)
### Overview

We need to implement a loading modal that clarifies who our organization is while also cueing the user that data is still being loaded because the current implementation is ambiguous.

### Action Items

- [x] Modify the FactModal to make use of a click-trap (no clicking out)
- [x] Adjust the modal backdrop to match the new Figma design
- [x] Add another div to the FactModal component that will contains the 311 logo, loading gif, about-us blurb, and modal-footer
- [x] Add a new state, prop, and callback for when the data is loaded in, e.g. `onDataLoaded`, ensure that the modal changes according to the design flow
- [x] Add a div that renders when the data is loaded which contains the header, 311 blurb, and OK button
- [x] Ensure that the modal remains open until the data has loaded, only closing when they click "OK"
- [x] (optional) Rename FactModal to LoadingModal, or some other name that indicates that more than fun facts are being communicated on the modal 

### Resources/Instructions
- Loading Gif is provided in a few frames by design team, you may need to compile this into a gif, perhaps ask Design for assistance
- MUI Modal component [docs](https://mui.com/material-ui/react-modal/)
- https://github.com/hackforla/311-data/issues/1655
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=9976%3A4824&mode=design&t=oszLfQ2mS8mbJtIx-1)

<details><summary>Screenshot of Figma Section</summary>
<p>

Loading Modal for Handoff 02 28 2024

</p>
</details>

### PR DESCRIPTION
**Pull request by Skydodle**
Fixes #1676

### Pre-Merge Checklist
  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [x] All PR Status checks are successful
  - [x] Peer reviewed and approved

### Changes made
- Created separate modals for Loading, Fun Fact, and Acknowledgement
- Loading Modal:
    - Removed the gradient loading bar under nav 
    - Added loading modal with 311 logo, spinner animation, blurb, footer
    - Added click-trap logic so user can't click outside to get out of modal or backdrop and cant interact with map
- Fun Fact Card:
    - Changed component from Modal to Card to prevent dual backdrop issues from MUI Modal's default backdrop prop
    - Moved original FactModal logic to FunFactCard
    - Updated content and styling to match Figma design
- Acknowledge Modal:
    - Added modal to match design
    - Added conditional render to show AcknowledgeModal when db and map finish loading
    - Click-trap: added logic user can only close the modal and backdrop by clicking the 'ok' button
- Updated MUI styling to v5 in these 3 components (ie. no longer using 'makeStyle' from v4 and use 'styled' from v5 instead)

Note: The background looks different than Figma design because the map in design file(some kind of dark mode map from older version?) is not up to date, but the backdrop is there and it disables user interaction with the map until 'ok' button is clicked as required

### Screenshots of before and after
<details><summary>Before</summary>
<p>

Screenshot 2024-03-29 at 12 57 05 PM

</p>
</details> 
<details><summary>After</summary>
<p>

Screenshot 2024-03-29 at 12 57 21 PM

</p>
<p>
Screenshot 2024-03-29 at 12 57 31 PM

</p>
</details>

### CODE REVIEW

**Review by sophia-bui — APPROVED** [review]
Hi Johnny, 
- The code was well-written, clean, and organized. Great for other developers to understand and change if needed.
- I tested the links / button on the modals. While waiting for the data to load, I tested on clicking on the modals and outside. Images / spinner is appropriate.
- Everything works as expected for this feature. Once moving past the feature as a user, the website works as expected.
- Amazing work! Approved.

**Review by bphan002 — APPROVED** [review]
The fact modal has been added and exactly matches the figma design.  I did notice they mentioned the background to be a specific opacity/darkness.  It is currently a bit light, but I'm not sure if that is a big issue.

The funfact component was well written, as well as the LoadingModal.  Great job Johnny!

**Review by ryanfchase — APPROVED** [review]
Cloned and tested locally, LGTM!

**Comment by Skydodle** [comment]
> The fact modal has been added and exactly matches the figma design. I did notice they mentioned the background to be a specific opacity/darkness. It is currently a bit light, but I'm not sure if that is a big issue.
> 
> The funfact component was well written, as well as the LoadingModal. Everything works perfectly as outlined.
> 
> Great job Johnny!

@bphan002 Hi Billy, thank you so much for your review. 

Regarding the backdrop opacity, the default backdrop that came with MUI's Modal component opacity is 0.5, which is slightly darker than the 0.4 opacity requested by the design team. In the design file provided, they seemed to be using an outdated version of the map with a dark background. Our current map has a light background, which would explain why it appears lighter even though the opacity is technically darker. 

After testing various opacities, I found that 0.5 visually achieves the desired level of transparency without making darker areas, like the navigation bar, too dark and indiscernible. I used the navigation bar as a point of darkness comparison between the UX design and my local development version since the map portion cannot be used for this comparison.

For these reasons I decided to keep the default opacity 0.5 and not customize it further.

I hope this addresses your concern. Thank you so much!

**Pull request merged**
