### PR TITLE
1778 migrate from webpack to vite

### LINKED ISSUE #1778: migrate build tooling from webpack to Vite
### Overview

We'd like to propose an alternative build tool in order to make it easier to implement tests for our frontend testing framework

### More Info (optional)

Vite is a [popular](https://2023.stateofjs.com/en-US/awards) open-source frontend build tool that offers HMR (hot module reloading), which means that saving changes to files during development can update the dev server almost instantly (< 50 milliseconds, [source](https://vitejs.dev/guide/features.html#transpile-only)).

Hey team, I've made progress on the testing ticket #1334 (and got some unit tests working), but I've been having some difficulty configuring Babel/Jest to run further tests.

In my experience, Vite/Vitest are much simpler to set up than webpack/Jest. I got curious and wanted to see if I could replace webpack in our repo with Vite. I managed to get HMR working in about half an hour (see screen recording below!) and figured this would improve everyone's developer experience a lot.

@ryanfchase I'd like to propose deprioritizing tests in favor of upgrading our build tooling. This would be a huge win for a lot less effort, and as a bonus it will become easier to implement tests.

### Action Items

- [x] install Vite package
- [x] get MVP Vite dev server running
   - [x] rename .js files to .jsx if they contain JSX
- [x] port other webpack.config.js options to vite.config.js
- [x] uninstall webpack/Babel-related packages
- [x] verify that `vite build` + `vite serve` builds and serves the site locally
- [x] verify that the Vite-built site runs on GitHub Pages

### Resources/Instructions

- https://vitejs.dev/

#### hot reloading demo

`⌘S` is shown in the lower left corner of my screen on save; you can see that changes to AcknowledgeModal.jsx are reflected in the browser in less than a second, without triggering a reload of the entire page

https://github.com/hackforla/311-data/assets/9038965/f2f2b6af-7e74-423c-a1fe-8dcce11d8680

### Dependency
- [x] need to complete https://github.com/hackforla/311-data/issues/1824

### LINKED ISSUE #1824: Modify CheckEnv.js to notify dev if Vite keys are missing from .env file
### Overview

We need to modify our `check-env` script to notify the dev if they are using non-vite compatible environment variables so that we can ensure previous devs have migrated to Vite.

### Action Items

- [x] check keys with checkEnv.js and determine if VITE_ prefix exists, add the prefix if it is not present
- [x] notify the dev if the prefix was added

### Resources

Info about relevant files
- in package.json
  -  start command: ` "start": "npm run check-env && npm run dev",`
  -  check-env command: `"node ./utils/checkEnv"`
- checkEnv.js
  - `utils/checkEnv.js`

### Archived Info

<details><summary>Details</summary>
<p>

> 
> ### Overview
> 
> This change is a simple variable renaming, which must be done for everyone running 311-Data after we switch from webpack to Vite. It could be done manually by inserting `VITE_` at the beginning of their .env file. Or we could automate it, for example by modifying [checkEnv.js](https://github.com/hackforla/311-data/blob/d68ff874b7433344d26fe0f92865a9502e700cc8/utils/checkEnv.js).
> 
> Additionally, the repository secret must be updated so that the Mapbox API key is available in GitHub Actions. See https://github.com/hackforla/311-data/issues/1778#issuecomment-2316193782
> 
> ### Action Items
> - [x] determine the best method for renaming this variable for all 311-Data developers (manual or using a script)
> - [ ] ensure that this variable is renamed for everyone by the time #1822 is merged
> - [ ] add/update the correctly-named repository secret by the time #1822 is merged
> 
> ### Resources/Instructions
> None

</p>
</details>

### PR DESCRIPTION
**Pull request by aqandrew**
closes #1778 
closes #1824 

  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [x] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Comment by traycn** [comment]
Review ETA: Fri 9/13 at 2PM PT

**Review by traycn — COMMENTED** [review]
This is running great! Appreciate your time in migrating from Webpack to Vite. There's a noticable difference in how quickly the app loads on changes.

Leaving a note on using Babel in the future. 

@vitejs/plugin-react provides Babel plugins/presets.
[Docs for @vitejs/plugin-react](https://www.npmjs.com/package/@vitejs/plugin-react)

----

Changes to running the application locally as of today.

Updates for developers: 
(refer to [#1824](https://github.com/hackforla/311-data/issues/1824) to remove this step)
- [ ] Update .env file
  - [ ] Pre-pend variable with `VITE_`, e.g.: `VITE_MAPBOX_TOKEN=..`

 
Update README.md
- [ ] Change `Visit http://localhost:3000/` to `Visit http://localhost:5173/`

**Comment by traycn** [comment]
Commenting an approval for this branch.

Once we've decided on a solution for [#1824](https://github.com/hackforla/311-data/issues/1824) and @ryanfchase reviews, it's good to merge.

**Comment by bphan002** [comment]
### General Notes for PR for documentation

- Artifacts removed (webpack)
- Accessing environment data from process to import.meta in (Reports.jsx, useContentful.jsx, data.js, store.js)
- Changing build and serve commands in package.json

**Comment by aqandrew** [comment]
Thanks for the docs @bphan002! I understand that not commit messages alone aren't the best way to document changes lol.

> .env file variables need to change with Vite prefix (unsure why this is required)
- Vite specifies that only environment variables prefixed with `VITE_` will be exposed to client-side code. ([see Vite docs](https://vitejs.dev/guide/env-and-mode.html#env-files))

> Line 139 of Mapsearch.jsx (Is this a bug fix or a Vite change?)
- This is a bug fix. Our webpack build doesn't log an error in DevTools when `removeListeners` is called, but Vite does. The function must be accessed from `this`, because it's a method of the `MapSearch` class.

> In DbProvider.jsx we are tracking certain Duckdb variables (curious of benefits on how it is better convention)
- Correct, accessing these DuckDB artifacts directly from the installed Node package `@duckdb/duckdb-wasm` eliminates the need for an external script. It also ensures we're using the most up-to-date versions of these artifacts. Previously we had to manually execute the [bundle.mjs](https://github.com/hackforla/311-data/blob/d68ff874b7433344d26fe0f92865a9502e700cc8/public/bundle.mjs) script from the command line, to copy the artifacts into the `public/` directory so that they could be made available to webpack. This could lead to us referencing out-of-date files if the `@duckdb/duckdb-wasm` package is updated without us re-running bundle.mjs.

**Comment by aqandrew** [comment]
Made some updates today to address #1824. Everyone who develops 311-Data will receive an alert from their browser when running locally if they haven't renamed their environment variables to be compatible with Vite (or if their .env file doesn't exist). This alert also includes instructions to automatically fix this by running the checkEnv.js script.

## Display an alert in local dev server if `VITE_MAPBOX_TOKEN` is missing from .env

This only occurs in dev mode (not in prod).

image

## Updated .example.env to use `VITE_` prefixes for vars that client-side code needs to access

Also made this change for the Contentful space id and Contentful token, since they're referenced in the `useContentful` hook:

https://github.com/hackforla/311-data/blob/26599df28cc5339e10b6f129dc343c7335aa95c5/hooks/useContentful.js#L4

https://github.com/hackforla/311-data/blob/26599df28cc5339e10b6f129dc343c7335aa95c5/hooks/useContentful.js#L15

## Modifed checkEnv.js to rename env vars for Vite if necessary

Screenshot below shows the terminal output of `npm run check-env`, with the following initial conditions in my .env file:

- `MAPBOX_TOKEN`, `CONTENTFUL_SPACE` using their old names (not prefixed with `VITE_`)
- deleted `HUGGINGFACE_LOGIN_TOKEN`, to validate that there weren't any regressions on the current behavior of checkEnv.js

image

**Review by ryanfchase — APPROVED** [review]
Tested this last week, this is looking good! Approved! 🎉

**Review by traycn — APPROVED** [review]

**Review by ryanfchase — CHANGES_REQUESTED** [review]
see comment here: https://github.com/hackforla/311-data/issues/1778#issuecomment-2423616070

**Review by ryanfchase — APPROVED** [review]
Approving after showing that specifying the `base` URL fixes the missing assets problem:
- changing `base` to match my repo's name: https://github.com/hackforla/311-data/issues/1778#issuecomment-2430329390
- https://github.com/hackforla/311-data/issues/1778#issuecomment-2433698990

**Pull request merged**
