### PR TITLE
Remove archive folder

### LINKED ISSUE #1690: Create archive branch for AWS frontend code and delete the archive folder
### Overview
We need to get rid of `archive/*` since it confuses IDE functionality, and devs accidentally commit to the archived versions of relevant files, causing confusion and wasting time.

### Action Items

Part 1
- [x] create a branch named `archive-aws-frontend`, and modify the code so that the contents of `archive/aws/client` replace the root of the `311-data` repo
- [x] commit this branch (no PR required)

Part 2
- [ ] On a feature branch (do not use `archive-aws-frontend`), delete the `archive` folder and submit a PR

### PR DESCRIPTION
**Pull request by ryanfchase**
Fixes #1690

### What changes did you make?
  - Removed the `archive` folder from the home directory

### Why did you make the changes (we will use this info to test)?
  - the `archive` folder is now properly stored on `archive-aws-frontend` within this repo and no longer needs to be included with the latest code on `main`

### Other Info
- no changes made to public facing features

  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Comment by sophia-bui** [comment]
I did some testing and overall, it seems to be working great! Filters are working and the tabs above show content as planned. I noticed a couple things that may or may not be affected. If these are not issues, then I can approve! @ryanfchase 

1. There is a modal that a pops up every time I change the date range (in the case a user wanted to look at a different neighborhood/date). This may be inconvenient to see multiple times during a session. See image below.
Screenshot 2024-03-07 at 12 53 36 PM


2. The current week has no data. I had to go back a week on the calendar to conduct testing.

**Comment by sophia-bui** [comment]
Actually, I tested it with the main branch for these points I found. Both branches act the same, so I will approve this now! LGTM @ryanfchase

**Review by sophia-bui — APPROVED** [review]
Actually, I tested it with the main branch for these points I found. Both branches act the same, so I will approve this now! LGTM @ryanfchase

**Comment by ryanfchase** [comment]
> I did some testing and overall, it seems to be working great! Filters are working and the tabs above show content as planned. I noticed a couple things that may or may not be affected. If these are not issues, then I can approve! @ryanfchase
> 
> 1. There is a modal that a pops up every time I change the date range (in the case a user wanted to look at a different neighborhood/date). This may be inconvenient to see multiple times during a session. See image below.
> 2. The current week has no data. I had to go back a week on the calendar to conduct testing.

Thanks @sophia-bui ya I've noticed how the modal pops-up again while data is being reloaded. I'm hoping this will get brought up when we do our next round of usability testing.

Same for lack of data this week, not sure what's going on with data.lacity.org, but we'll keep an eye on it.

**Review by Skydodle — APPROVED** [review]
@ryanfchase I pulled down the PR branch and tested the site locally, the map visualization and filters were working correctly, and all other page routes (Contact, FAQ, About, Privacy) were also rendering correctly. I also noticed the data for March is not coming in but it's not likely related to this issue. Looks like this is a successful removal of the archive files that honey-trapped devs for months, thank you so much Ryan!

One minor suggestion is to add some details on the PR so that in the future when someone for some reason is backtracking this issue, they would get up to speed quickly on what you did. For example, the archive files were moved to a new branch to be stored, maybe specify in the PR what's the name of this branch?

**Comment by funbunch** [comment]
Hey @ryanfchase, I checked this out too, and got the same results as those above. I'm still getting the modal pop up and March data not coming in, but otherwise good to me!

**Review by funbunch — APPROVED** [review]

**Comment by ryanfchase** [comment]
> @ryanfchase I pulled down the PR branch and tested the site locally, the map visualization and filters were working correctly, and all other page routes (Contact, FAQ, About, Privacy) were also rendering correctly. I also noticed the data for March is not coming in but it's not likely related to this issue. Looks like this is a successful removal of the archive files that honey-trapped devs for months, thank you so much Ryan!
> 
> One minor suggestion is to add some details on the PR so that in the future when someone for some reason is backtracking this issue, they would get up to speed quickly on what you did. For example, the archive files were moved to a new branch to be stored, maybe specify in the PR what's the name of this branch?

@Skydodle that's a good note about updating info on the PR, I've included the relevant info within the description, thank you! 🙏

**Pull request merged**
