### PR TITLE
#3 v2 header & footer updates

### PR DESCRIPTION
**Pull request by edwinjue**
Contributes to #1347

### Header ([figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5170%3A29181))
image

### Header (#1389)
image

### Footer ([figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5170%3A29181))
image

### Footer (#1389)
image

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Comment by edwinjue** [comment]
@jekijo The third one for you Killen. Please let me know if you have any questions. Thanks again!

**Comment by edwinjue** [comment]
@funbunch added you as a reviewer since you have been recently working on these files. Please let me know if you have any questions. Thanks in advance!

**Comment by funbunch** [comment]
Hi @edwinjue Is there a visual change here where we can see a screenshot?

**Comment by edwinjue** [comment]
@funbunch good idea! i just updated the first post with screenshots of what the header and footer will look like after merge along with screenshots taken from the figma v2 design. hope it helps

**Comment by funbunch** [comment]
Thanks! Will approve.

**Review by funbunch — APPROVED** [review]

**Comment by edwinjue** [comment]
@funbunch Thanks, appreciate the quick response!

**Pull request merged**
