### PR TITLE
adding postgis and council geojson

### LINKED ISSUE #909: [FEAT] Load council geometries and serve geojson from API
# Description

Want to load the current GeoJSON into the database and create and endpoint that will serve it up from the API. 

The immediate benefit is that the client won't need to bundle the (huge) file and we'll be able to update the GeoJSON without needing new client releases.

The longer term benefits are that we'll be able to do spatial queries in the app (e.g. calculate centroids, query for points by distance, etc.). We will also be able to automate the process of downloading the new GeoJSON when there are changes.

## Action Items

1. Need to use postgis docker image
2. Need to enable postgis extension with alembic
3. Need to load a table with geometry (MULTIPOLYGON) from current GeoJSON
4. Need to add model and ORM query
5. Need to add endpoint

## Resources
https://geoalchemy-2.readthedocs.io/en/latest/orm_tutorial.html
https://geohub.lacity.org/datasets/neighborhood-councils-certified/
https://postgis.net/docs/reference.html#Geometry_Accessors
https://github.com/jgriffith23/postgis-tutorial

### PR DESCRIPTION
**Pull request by mattyweb**
Fixes #909 

Adding PostGIS support
Adding council GeoJSON and endpoint (/geojson) for client

### CODE REVIEW

**Comment by mattyweb** [comment]
I need to add some tests.
And probably rename some stuff.

**Comment by jafow** [comment]
Looking good to me. I do not have enough context I think to be generally helpful but I think the setup here is 👌👌

**Review by adamkendis — APPROVED** [review]
Looks good to me. Only thing I noticed was that some of the precision on the coordinates has been lost, but I really don't know if we even need something like 14-16 decimal places on lat/lng. Couple comparison snippets below. Not sure if that's caused by casting geometry to string or something else. We can put it on dev and see how it looks in the client.

**seeds/nc-boundary-geojson.json
nc_id: 6**
```
"coordinates": [
  [
    [
      [
          -118.45005171864273,
          34.249915100597775
      ],
      [
          -118.45055441819916,
          34.2506346000586
      ],
      [
          -118.451585617486,
          34.2516467005137
      ],
```

sample json response you sent in slack
nc_id: 6
```
"coordinates": [
  [
    [
      [
        -118.450051719,
        34.249915101
      ],
      [
        -118.450554418,
        34.2506346
      ],
      [
        -118.451585617,
        34.251646701
      ],
```

**Comment by mattyweb** [comment]
per discussion on Slack, i think we're OK with losing some precision here (I think it was false accuracy).

i've also decided to push a separate PR to add some tests...there's some other stuff i want to refactor there anyway.

**Pull request merged**
