### PR TITLE
1127-nav-hoverContrast change hover to red

### LINKED ISSUE #1127: Navigation hover contrast
When hovering over the navigation bar on top of the page, it is difficult to see the hover color when the mouse hovers over the text due to the lack of color contrast.

### PR DESCRIPTION
**Pull request by ezhou0**
Fixes #1127

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

### CODE REVIEW

**Review by KristenDLR — APPROVED** [review]
Looks good to me!

**Comment by EchoProject** [comment]
Please provide a screenshot of the before and after views.

**Comment by ezhou0** [comment]
Screen Shot 2021-12-06 at 7 15 09 PM
Screen Shot 2021-12-06 at 7 15 16 PM

-Selecting Select All selects all not already selected filter types and updates state. Deselecting Select All deselects all not already deselected filter types and updates state

**Comment by ezhou0** [comment]
Screen Shot 2021-12-06 at 10 58 23 PM
Screen Shot 2021-12-06 at 10 58 34 PM
ubusercontent.com/36352637/144981633-325edbeb-5c08-4eff-bdf0-99d8384b6937.png">

Properly shows underline under the navlink of the active page. 
DOES NOT show underline onclick for reports because it is a dropdown not a navlink. 
REMOVED red hover and went back to default MUI button hover

**Review by adamkendis — APPROVED** [review]
LGTM!

**Comment by adamkendis** [comment]
I'll fix the build pipeline and merge this in over the weekend unless you beat me to it.

**Comment by nichhk** [comment]
My best guess ATM for the build failure is that GitHub Actions [upgraded](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/) the default Node version to 16, right around the time that the build failures began.

This guess is corroborated by the fact that `npm run setup` (from [client setup](https://github.com/hackforla/311-data/tree/dev/client#readme)) failed when I was using Node 18, but succeeds when I use Node 12. I knew I should try using Node 12 because the first error I got when running `npm run setup` was:

`npm ERR! code 1
npm ERR! path /Users/nich/hackforla/311-data/client/node_modules/node-sass`

which points out node-sass; I checked the [package.json](https://github.com/hackforla/311-data/blob/dev/client/package.json#L94) file, and it requires a fairly old version of node-sass (see mapping from node-sass to Node versions [here](https://github.com/sass/node-sass#node-version-support-policy)). 

Every Action should specify to use Node 12 using [setup-node](https://github.com/actions/setup-node). I will check if this works and create a new PR if so. We can also explore upgrading node-sass, but the former solution seems like the smallest one.

Regardless of whether that's the fix, we should make it plainly obvious what version of Node we expect to run on. We can do that by stating it in the package.json file (see stackoverflow [question](https://stackoverflow.com/questions/42805913/how-to-find-what-node-version-a-project-supports)).

**Comment by nichhk** [comment]
#1183 merged into dev, and I merged dev back into this branch. The tests pass now, so I will merge this PR into dev.

**Pull request merged**
